# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJNTp24wKf-8zOas3A6_0bJTh1F8Zzc2
"""

pip install gspread oauth2client streamlit plotly

import streamlit as st
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime, date
import pandas as pd
import plotly.express as px

# Google Sheet setup
scope = ["https://spreadsheets.google.com/feeds",'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name("/content/sample_data/service_account.json", scope)
client = gspread.authorize(creds)
sheet = client.open("Mood Queue Log").sheet1  # Rename to your actual sheet name

# UI
st.title("🧠 Mood of the Queue")

# Mood Logging
mood = st.selectbox("Select your mood:", ["😊", "😠", "😕", "🎉"])
note = st.text_input("Optional note:")
if st.button("Submit"):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sheet.append_row([timestamp, mood, note])
    st.success("Mood logged!")

# Mood Visualization
st.header("Today's Mood Summary")
records = sheet.get_all_records()
df = pd.DataFrame(records)
if not df.empty:
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df_today = df[df['timestamp'].dt.date == date.today()]
    if not df_today.empty:
        mood_counts = df_today['mood'].value_counts().reset_index()
        mood_counts.columns = ['mood', 'count']
        fig = px.bar(mood_counts, x='mood', y='count', title="Mood Counts Today", color='mood')
        st.plotly_chart(fig)
    else:
        st.info("No mood entries for today yet.")
else:
    st.info("No mood data logged yet.")